# Generated by Django 5.1 on 2024-11-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechaentrega',
            field=models.DateTimeField(null=True),
        ),
    ]
