# Generated by Django 5.1 on 2024-12-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_app', '0002_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='osorno', max_length=20),
        ),
    ]
