# Generated by Django 5.0.4 on 2024-12-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_app', '0003_usuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=76),
        ),
    ]
