# Generated by Django 5.1 on 2024-11-26 21:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario_app', '0002_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nOrden', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('escorrecto', models.BooleanField(default=False)),
                ('seleccionado', models.BooleanField(default=False)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Respuestas', to='Trivia_app.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=25)),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaTermino', models.DateTimeField()),
                ('fechaResuelto', models.DateTimeField(null=True)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('usuarioCreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trivias_Creadas', to='Usuario_app.usuario')),
                ('usuarioModificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trivias_Modificadas', to='Usuario_app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Preguntas', to='Trivia_app.trivia'),
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaTermino', models.DateTimeField()),
                ('valor', models.FloatField(default=0.0)),
                ('usuPropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='Usuario_app.usuario')),
                ('id_trivia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='Trivia_app.trivia')),
            ],
        ),
    ]
