# Generated by Django 5.1 on 2024-11-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
