# Generated by Django 5.1 on 2024-12-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_app', '0003_trivia_usuariorealizados_descuentos_delete_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='usuarioModificacion',
        ),
        migrations.AddField(
            model_name='descuentos',
            name='estado',
            field=models.CharField(default='invalido', max_length=25),
        ),
        migrations.AddField(
            model_name='trivia',
            name='descuentoofrecido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
