# Generated by Django 5.1 on 2024-12-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_app', '0004_remove_trivia_usuariomodificacion_descuentos_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='fechaResuelto',
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='id_trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='Trivia_app.trivia'),
        ),
    ]
