# Generated by Django 5.1 on 2024-11-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Platillo_app', '0004_platillo_codigo'),
        ('Usuario_app', '0002_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carrito', to='Platillo_app.platillo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='Usuario_app.usuario')),
            ],
        ),
    ]
