# Generated by Django 5.1 on 2024-11-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platillo_app', '0002_platillo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
