# Generated by Django 5.1 on 2024-11-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0002_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(max_length=25),
        ),
    ]
